config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'students/show'
  get 'students/create'
  get 'students/edit'
  get 'welcome/index'
  get '/returnBook', to: 'borrowings#returnBook', as: 'returnBook'
  root 'welcome#index'
  resources :students, :books, :borrowings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :borrowings, dependent: :destroy
end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :Student
  belongs_to :Book
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :borrowings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
	end
	def show
		@book = Book.find(params[:id])
	end
	def create
		#render plain: params[:book].inspect

		@book = Book.new(book_params)

		@book.save
		redirect_to @book

	end
	def edit
		@book = Book.find(params[:id])
	end
	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to books_path
		else
			render 'edit'
		end
	end
	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end
	private
	def book_params
		params.require(:book).permit(:name, :author, :pages, :price, :subject)
	end
end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
	protect_from_forgery except: :returnBook
	#helper_method :returnBook
	def index
		@borrowings = Borrowing.where(:isReturned => false)
	end
	def create
		@borrowing = Borrowing.new(borrowing_params)
		if Book.where({id: @borrowing.Book_id,isBorrowed: false}).present?
			@borrowing.save
			Book.update(@borrowing.Book_id, :isBorrowed => true)
			redirect_to @borrowing
		else
			@msg = "Book with id:#{@borrowing.Book_id} is currently unavailable"
			render action: 'new', notice: 'Sample notice'
		end
	end
	def show
		flash.now[:alert] = "Showing"

		@borrowing = Borrowing.find(params[:id])
		@student = Student.find(@borrowing.Student_id)
		@book = Book.find(@borrowing.Book_id)

	end
	def returnBook
		#render plain: params[:id].inspect

		Book.update(params[:id], :isBorrowed => false)
		Borrowing.update(params[:my_param], :isReturned => true)
		redirect_to borrowings_path
	end

	private
	def borrowing_params
		params.require(:borrowing).permit(:Student_id, :Book_id)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  	@students = Student.all
    
  end

  def show
    @student = Student.find(params[:id])
  end
  def new
  	
  end
 
  def create
  	#render plain: params[:student].inspect

  	@student = Student.new(student_params)
  	@student.save
    
  	redirect_to @student

  end

  def edit
    @student = Student.find(params[:id])
  end
  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end
  def destroy
    @student = Student.find(params[:id])

    @student.destroy

    redirect_to students_path
  end
  private 
  def student_params
  	params.require(:student).permit(:roll_no,:name,:class_,:phone, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/edit.html.erb
<div class="my-container theme-showcase" role="main">
  <div class="my-jumbotron">
    <h4>Edit Book Details</h4>

    <%= form_with(model: @book, local:true) do |form| %>
    	<table class="table table-striped" style="width: 100%;">
    		<tr><td><%= form.label :name %></td><td><%= form.text_field :name %></td></tr>
    		<tr><td><%= form.label :author %></td><td><%= form.text_field :author %></td></tr>
    		<tr><td><%= form.label :pages %></td><td><%= form.text_field :pages %></td></tr>
    		<tr><td><%= form.label :price %></td><td><%= form.text_field :price %></td></tr>
    		<tr><td><%= form.label :subject %></td><td><%= form.select(:subject, options_for_select([['Select','select'],['Physics', 'phy'], ['Chemistry', 'chem'], ['Mathematics','math']])) %></td></tr>
    		<tr><td></td><td><%= form.submit 'Update', :class=>'btn btn-success' %></td></tr>
    	</table>
    <% end %>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Back', books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="my-container theme-showcase" role="main">
  <div class="my-jumbotron">
	<h4>Showing All Books</h4>
	<table class="table table-striped" style="width: 100%;">
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Author</th>
			<th>Pages</th>	
			<th>Price</th>
			<th>Subject</th>
			<th>Borrowed</th>
			<th>Show</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		<% @books.each do |book| %>
			<tr>
				<td><%= book.id %></td>
				<td><%= book.name %></td>
				<td><%= book.author %></td>
				<td><%= book.pages %></td>
				<td><%= book.price %> &#8377;</td>
				<td><%= book.subject %></td>
				<td><%= book.isBorrowed %></td>
				<td><%= link_to 'Show', book_path(book) %></td>
				<td><%= link_to 'Edit', edit_book_path(book) %></td>
				<td><%= link_to 'Delete',book_path(book), method: :delete, data:{confirm: 'Are you sure?'} %></td>
			</tr>
		<% end %>
			
	</table>
	<%= link_to 'Home', root_path %> |
	<%= link_to 'Add New Book', new_book_path %>
</div>
</div>
</div>

app/views/books/new.html.erb
<div class="my-container theme-showcase" role="main">
	<div class="my-jumbotron">
	<h3>Add New Books</h3>
		<%= form_with scope: :book, url: books_path, local: true do |form| %>
			<table class="table table-striped" >
				<tr><td><%= form.label :name %></td><td><%= form.text_field :name %></td></tr>
				<tr><td><%= form.label :author %></td><td><%= form.text_field :author %></td></tr>
				<tr><td><%= form.label :pages %></td><td><%= form.text_field :pages %></td></tr>
				<tr><td><%= form.label :price %></td><td><%= form.text_field :price %></td></tr>
				<tr><td><%= form.label :subject %></td><td><%= form.select(:subject, options_for_select([['Select','select'],['Physics', 'phy'], ['Chemistry', 'chem'], ['Mathematics','math']])) %></td></tr>
				<tr><td></td><td><%= form.submit 'Submit', :class => 'btn btn-success' %></td></tr>
			</table>
			<%= link_to 'Home', root_path %> | 
			<%= link_to 'Back', books_path %>
		<% end %>	
</div>
</div>

app/views/books/show.html.erb
<div class="my-container theme-showcase" role="main">
	<div class="my-jumbotron">
	<h3>Showing Book Details</h3>
	<table class="table table-striped">
		<tr><td>Name</td><td><b><%= @book.name %></td></b></tr>
		<tr><td>Author</td><td><b><%= @book.author %></td></b></tr>
		<tr><td>Pages</td><td><b><%= @book.pages %></td></b></tr>
		<tr><td>Price</td><td><b><%= @book.price %> &#8377; </b></td></tr>
		<tr><td>Subject</td><td><b><%= @book.subject %></b></td></tr>
	</table>
	<%= link_to 'Home', root_path %> |
	<%= link_to 'Back', books_path %> |
	<%= link_to 'Add New Book', new_book_path %>
	</div>
</div>

app/views/borrowings/edit.html.erb
<div class="my-container theme-showcase" role="main">
	<div class="my-jumbotron">
		<h4>Edit Borrowings</h4>
		<table class="table table-striped">
		</table>
	</div>
</div>

app/views/borrowings/index.html.erb
<div class="my-container theme-showcase" role="main">
	<div class="my-jumbotron">
		<h4>Showing All Borrowings</h4>
		<table class="table table-striped">
			<tr>
				<th>Id</th>
				<th>Student Name</th>
				<th>Book Name</th>
				<th>Is Returned</th>
				<th>Issued On</th>
				<th>Show</th>
				<th>Return Book</th>
			</tr>
			<% @borrowings.each do |borrowing| %>

			<tr>
				<td><%= @id = borrowing.id %></td>
				<td><%= Student.find(borrowing.Student_id).name %></td>
				<td><%= Book.find(borrowing.Book_id).name %></td>
				<td><%= borrowing.isReturned %> </td>
				<td><%= borrowing.created_at %></td>
				<td><%= link_to 'Show', borrowing_path(borrowing) %></td>
				<td><%= link_to "Return", {controller:"borrowings", action:"returnBook", my_param: borrowing.id, id: borrowing.Book_id}, id: borrowing.id %></td>

			</tr>
			<% end %>
		</table>
		<%= @msg %>
		<%= link_to 'Home', root_path %> |
		<%= link_to 'Issue a Book', new_borrowing_path %>
	</div>
</div>

app/views/borrowings/new.html.erb
<div class="my-container theme-showcase" role="main">
	<div class="my-jumbotron">
		<h4>Add New Borrowing</h4>
		<%= form_with scope: :borrowing, url: borrowings_path, local: true do |form| %>
		<table class="table table-striped">
			
			<tr><td><%= form.label :Student_id %></td><td><%= form.collection_select(:Student_id, Student.all, :id, :name, {:prompt => true}, {class: "newdropdown-menu", id: "newdropdown"}) %></td></tr>
			<tr><td><%= form.label :Book_id %></td><td><%= form.collection_select(:Book_id, Book.all, :id, :name, {:prompt => true}, {class: "newdropdown-menu", id: "newdropdown"}) %></td></tr>
			<tr><td></td><td><%= form.submit 'Issue', :class=>'btn btn-success' %></td></tr>
			<tr><td></td><td></td></tr>
		</table>
		<p id="notice"><%= @msg %></p>
		<% end %>
		<%= link_to 'Home', root_path %> |
		<%= link_to 'Back', borrowings_path %>
	</div>
</div>

app/views/borrowings/show.html.erb
<div class="my-container theme-showcase" role="main">
	<div class="my-jumbotron">
		<h4>Show Borrowings</h4>
		
		<table class="table table-striped">
			<tr><td>Student Id</td><td><%= @borrowing.Student_id %></td></tr>
			<tr><td>Book Id</td><td><%= @borrowing.Book_id %></td></tr>
			<tr><td><%= @book.name %></td><td><%= @student.name %></td></tr>
		</table>
		<%= link_to 'Home', root_path %> |
		<%= link_to 'Back', borrowings_path %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<div class="my-container theme-showcase" role="main">
  <div class="my-jumbotron">
	<h4>Edit Students</h4>
	<%= form_with(model: @student, local:true) do |form | %>
		<table class="table table-striped">
			<tr><td><%= form.label :roll_no %></td><td><%= form.text_field :roll_no %></td></tr>
			<tr><td><%= form.label :name %></td><td><%= form.text_field :name %></td></tr>
			<tr><td><%= form.label :class_ %></td><td><%= form.text_field :class_ %></td></tr>
			<tr><td><%= form.label :phone %></td><td><%= form.text_field :phone %></td></tr>
			<tr><td><%= form.label :email %></td><td><%= form.text_field :email %></td></tr>
			<tr><td></td><td><%= form.submit 'Update', :class=>'btn btn-success' %></td></tr>
		</table>
		<%= link_to 'Home', root_path %> |
		<%=  link_to 'Back', students_path %>
	<% end %>
	</div>
</div>

app/views/students/index.html.erb
<div class="my-container theme-showcase" role="main">
  <div class="my-jumbotron">
	<h4>Showing All Students</h4>
	<table class="table table-striped">
		<tr>
			<th>Id</th>
			<th>Roll Number</th>
			<th>Name of Student</th>
			<th>Class</th>
			<th>Phone Number</th>
			<th>Email</th>
			<th>Show</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		<% @students.each do |student| %>
	 	<tr>
	 		<td><%= student.id %></td>
	 		<td><%= student.roll_no %></td>
		 	<td><%= student.name %></td>
		 	<td><%= student.class_%></td>
	 		<td><%= student.phone %></td>
	 		<td><%= student.email %></td>
	 		<td><%= link_to 'Show', student_path(student) %>
	 		<td><%= link_to 'Edit', edit_student_path(student)%></td>
	 		<td><%= link_to 'Delete', student_path(student), method: :delete, data:{confirm: 'Are you sure?'} %></td>
	 	</tr>
		<% end %>
	</table>
	<%= link_to 'Home', welcome_index_path %>  |
	<%= link_to 'Add New Student', new_student_path %>
	
   </div>
</td>

app/views/students/new.html.erb
<div style="margin-left: 30%;margin-top: 10%;">
	<%= form_with scope: :student, url: students_path, local: true do |form| %>
		<h3>Add Student</h3>
		<table class="table table-striped" style="width:50%">
			<tr><td><%= form.label :roll_no %></td><td><%= form.text_field :roll_no %></td></tr>
			<tr><td><%= form.label :name %></td><td><%= form.text_field :name %></td></tr>
			<tr><td><%= form.label :class_ %></td><td><%= form.text_field :class_ %></td></tr>
			<tr><td><%= form.label :phone %></td><td><%= form.text_field :phone %></td></tr>
			<tr><td><%= form.label :email %></td><td><%= form.text_field :email %></td></tr> 
			<tr><td></td><td><%= form.submit 'Save', :class=> 'btn btn-success'%></td></tr>
		</table>
	<% end %>
	<%= link_to 'Home', welcome_index_path %>  |  
	<%= link_to 'Back', students_path %>
</div>

app/views/students/show.html.erb
<div class="my-container theme-showcase" role="main">
  <div class="my-jumbotron">
  <h4>Showing Student Details</h4>
	<table class="table table-striped">
		<tr><td>Roll Number</td><td><b><%= @student.roll_no %></b></td></tr>
		<tr><td>Name</td><td><b><%= @student.name %></b></td></tr>
		<tr><td>Class</td><td><b><%= @student.class_%></b></td></tr>
		<tr><td>Phone</td><td><b><%= @student.phone%></b></td></tr>
		<tr><td>Email</td><td><b><%= @student.email%></b></td></tr>
	</table>
	<%= link_to 'Home', root_path %> |
	<%= link_to 'Back', students_path %> | 
	<%= link_to 'Add New Student', new_student_path %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="my-container theme-showcase" role="main">
	<div class="my-jumbotron">
		<table class="table table-striped" style="width:100%;text-align: center;">
			<tr>
				<td colspan="3" style=""><h3>Library Manager</h3></td>
			</tr>
	    	<tr>
	    		<td><h4><%= link_to 'Manage Students', students_path %></h4></td>
	    		<td><h4><%= link_to 'Manage Books', books_path %></h4></td>
	    		<td><h4><%= link_to 'Manage Borrowings', borrowings_path %></h4></td>
	    	</tr>
		</table>
	</div>
</div>